spring:
  profiles:
    active: local
  application:
    name: springboot-dynamodb

dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT}
  region: ${DYNAMODB_REGION}
  table-name-suffix: ${DYNAMODB_TABLE_NAME_SUFFIX}